<?php

/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
 
//require_once get_stylesheet_directory() . '/action-scheduler.php';
 
date_default_timezone_set("America/Asuncion");
include_once $_SERVER['DOCUMENT_ROOT'] . '/api/logger.php';
function bacola_child_enqueue_styles()
{
    wp_enqueue_style('parent-style', get_template_directory_uri() . '/style.css');
    wp_enqueue_style(
        'bacola-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array('bacola-style'),
        wp_get_theme()->get('Version')
    );
    // 2) BlockUI desde CDN:
    wp_enqueue_script(
        'jquery-blockui',
        'https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js',
        array('jquery'),
        '2.70',
        true  // cargar en footer
    );
}

//add_action('wp_enqueue_scripts', 'bacola_child_enqueue_styles', 99);

function bacola_child_enqueue_assets() {
    // Estilos
    wp_enqueue_style(
        'parent-style',
        get_template_directory_uri() . '/style.css'
    );
    wp_enqueue_style(
        'bacola-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array('parent-style'),
        wp_get_theme()->get('Version')
    );

    // 1) BlockUI — dependiente de jQuery, en footer
    wp_enqueue_script(
        'jquery-blockui',
        'https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js',
        array('jquery'),
        '2.70',
        true
    );

}
add_action('wp_enqueue_scripts', 'bacola_child_enqueue_assets', 99);


if (!function_exists('ft_ajax_stock_check')) {
    require_once get_stylesheet_directory() . '/stock-validation.php';
    wp_enqueue_script('stock-error', get_stylesheet_directory_uri().'/js/stock-error.js', ['jquery','sweetalert2'], '1.0', true);
}

add_action('wp_enqueue_scripts', function(){
  wp_enqueue_script(
    'stock-intercept',
    get_stylesheet_directory_uri() . '/js/stock-intercept.js',
    ['jquery','sweetalert2'],
    '1.0',
    true
  );
  // Pasa el código ERP a JS
  wp_localize_script('stock-intercept', 'ft_params', [
    'erp_code' => obtener_codigo_erp_desde_cookie()
  ]);
});


/*function console_log($label, $data) {
    // Codificamos ambos por separado para que JS los entienda
    $js_label = json_encode($label);
    $js_data  = json_encode($data);

    echo '<script type="text/javascript">';
    // En JS, usamos coma (,) para imprimir múltiples cosas separadas
    echo "console.log($js_label, $js_data);"; 
    echo '</script>';
}*/

/*add_action('init', function () {
    if (is_admin()) {
        return;
    }

    global $wp_scripts;
    if (isset($wp_scripts->registered['jquery']->ver)) {
        $ver = $wp_scripts->registered['jquery']->ver;
    } else {
        $ver = '1.12.4';
    }

    wp_deregister_script('jquery');
    wp_register_script('jquery', "//ajax.googleapis.com/ajax/libs/jquery/$ver/jquery.min.js", false, $ver);
});*/

function allow_svg_upload($mimes)
{
    $mimes['svg'] = 'image/svg+xml';
    return $mimes;
}
add_filter('upload_mimes', 'allow_svg_upload');

function display_svg_in_media_library($response, $attachment, $meta)
{
    if ($response['type'] === 'image' && $response['subtype'] === 'svg+xml') {
        $response['html'] = wp_get_attachment_image($attachment->ID, 'full');
    }
    return $response;
}
add_filter('wp_prepare_attachment_for_js', 'display_svg_in_media_library', 10, 3);


function enqueue_custom_scripts()
{
    wp_enqueue_script('custom-scripts', get_stylesheet_directory_uri() . '/js/custom-scripts.js', array('jquery'), '1.0', true);
}
add_action('wp_enqueue_scripts', 'enqueue_custom_scripts');


add_action('woocommerce_before_add_to_cart_form', 'add_art_controlado_text');
function add_art_controlado_text()
{

    global $post;
    $product_id = $post->ID;
    $ArtControlado = get_post_meta($product_id, 'ind_controlado', true);
    if ($ArtControlado == 'S') {
        echo '<p class="badge-ft">Este producto requiere presentación de receta médica.</p>';
    }
}



add_filter('woocommerce_get_price_html', 'precio_web', 100, 2);
function precio_web($price, $product)
{
    if ($product->is_on_sale()) {
        $precio_web = str_replace('<ins aria-hidden="true">', '<br><ins><span class="woocommerce-Price-amount amount"><span class="precio-web" style="color: #444;font-weight: 600;">Precio Web: </span>', $price);
        return $precio_web;
    } else {
        return $price;
    }
}

add_filter('woocommerce_get_price_html', 'precio_normal', 100, 2);
function precio_normal($price, $product)
{
    if ($product->is_on_sale()) {
        $precio_normal = str_replace('<del aria-hidden="true">', '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><span class="precio-normal" style="color: #444;font-weight: 400;">Precio Normal: </span>', $price);
        return $precio_normal;
    } else {
        return $price;
    }
}

add_filter('woocommerce_get_price_html', 'precio_web_normal', 100, 2);
function precio_web_normal($price, $product)
{
    if (!$product->is_on_sale()) {
        $precio_normal = str_replace('<bdi>', '<span class="precio-web-normal" style="color: #444;font-weight: 600;">Precio Web: </span><bdi>', $price);
        return $precio_normal;
    } else {
        return $price;
    }
}


//add_filter('woocommerce_placeholder_img_src', 'bp_woo_placeholder', 10);
function bp_woo_placeholder($image_url)
{
    $image_url = get_site_url() . '/wp-content/uploads/no_img.webp';
    return $image_url;
}






function filter_products_by_discount_and_category($query)
{
    if (isset($_GET['descuento'])) {
        $discount_percentage = intval($_GET['descuento']);
        if ($discount_percentage >= 1 && $discount_percentage <= 100) {

            $query->set('meta_query', array(
                'relation' => 'AND',
                array(
                    'key' => 'porc_dcto',
                    'value' => $discount_percentage,
                    'compare' => '>=',
                    'type' => 'NUMERIC'
                )
            ));
        } else {
            // Si el porcentaje de descuento no está en el rango válido, establecer un valor que no coincida con ningún producto
            $query->set('meta_query', array(
                array(
                    'key' => 'porc_dcto',
                    'value' => -9999, // Un valor que no coincida con ningún producto
                    'compare' => '=',
                    'type' => 'NUMERIC'
                )
            ));
        }
    }
}

add_action('pre_get_posts', 'filter_products_by_discount_and_category');



/* INTEGRACION CON ERP */




function obtener_codigo_erp_desde_cookie()
{
    if (isset($_COOKIE['woocommerce_multi_inventory_inventory']) && !empty($_COOKIE['woocommerce_multi_inventory_inventory'])) {
        $location = intval($_COOKIE['woocommerce_multi_inventory_inventory']);
        $codigo_erp = get_term_meta($location, 'codigo_erp', true);
        return $codigo_erp;
    }

    // En caso de que la cookie no tenga un valor válido, puedes retornar null o algún otro valor predeterminado según tus necesidades.
    return null;
}


function obtener_sucursal()
{
    if (isset($_GET['location'])) {
        $location = $_GET['location'];
        $codigo_erp = get_term_meta($location, 'codigo_erp', true);
        return $codigo_erp;
    }
}

function wl8_get_medio_pago($payment_method_title)
{
    $medio_de_pago_map = array(
        'Efectivo (Contra Entrega)' => 1,
        'Tarjeta de Crédito (Contra Entrega)' => 2,
        'Tarjeta de Débito (Contra Entrega)' => 3,
        'Tarjeta de Crédito/Débito (Online)' => 2
    );
    return isset($medio_de_pago_map[$payment_method_title]) ? $medio_de_pago_map[$payment_method_title] : 0;
}
function wl8_get_metodo_envio($shipping_method)
{
    $metodo_envio_map = array(
        'Envío a Dirección (Delivery)' => 1,
        'Retiro en Sucursal (Pick-Up)' => 2
    );
    return isset($metodo_envio_map[$shipping_method]) ? $metodo_envio_map[$shipping_method] : 0;
}

function wl8_get_estado_pedido($status)
{
    $estado_pedido_map = array(
        'processing' => 'P',
        'completed' => 'C',
        'cancelled' => 'A',
        'pending' => 'P'
    );
    return isset($estado_pedido_map[$status]) ? $estado_pedido_map[$status] : '';
}

//add_action('woocommerce_thankyou', 'wl8OrderPlacedTriggerSomething', 10, 1);
function wl8OrderPlacedTriggerSomething($order_id)
{
    
    
    // Verificar si la función ya se ejecutó para este pedido
    if (get_post_meta($order_id, '_order_processed', true)) {
        return; // Evitar la ejecución duplicada
    }
    
    
    $fp = fopen($_SERVER['DOCUMENT_ROOT'] . '/api/response.txt', 'a+');
    $TrackError = fopen($_SERVER['DOCUMENT_ROOT'] . '/api/trackerror.txt', 'a+');
    $order = wc_get_order($order_id);
    $order_data = $order->get_data();

    // Obtener datos del cliente y envío desde metadatos del pedido
    $customer_data = array();
    foreach ($order->get_meta_data() as $item) {
        $item_data = $item->get_data();
        $keys_to_map = array(
            '_billing_nro_doc' => 'CLI_NRO_DOC',
            '_billing_tipo_doc' => 'CLI_TIPO_DOC',
            '_billing_razon_social' => 'CLI_RAZON_SOCIAL',
            'billing_lat' => 'ECO_LATITUD',
            'billing_long' => 'ECO_LONGITUD',
            'billing_sucursal' => 'ECO_ENV_SUC',
        );
        if (isset($keys_to_map[$item_data['key']])) {
            $customer_data[$keys_to_map[$item_data['key']]] = $item_data['value'];
        }
    }

    // Obtener otros datos del pedido
    $sucursal = obtener_codigo_erp_desde_cookie();
    //$sucursal_envio = obtener_sucursal();
    $direccion_envio = $order->get_billing_address_1();
    $pedido_ciudad = $order->get_billing_city();
    $depto_envio = $order->get_billing_state();
    $metodo_envio = wl8_get_metodo_envio($order->get_shipping_method());
    //$metodo_envio = $order->get_shipping_method();
    $medio_de_pago = wl8_get_medio_pago($order->get_payment_method_title());
    $estado_del_pedido = wl8_get_estado_pedido($order->get_status());
    $telefono_cliente = $order->get_billing_phone();
    $numero_pedido = $order->get_id();
    $numero_proceso = $order->get_order_key();
    $cli_cogido = $order->get_customer_id();
    $total_descuento = $order->get_discount_total();
    $cupon = $order->get_coupon_codes();
    $nota_pedido = $order->get_customer_note();
    $order_total = $order->get_total();

    // Obtener detalles de los productos del pedido
    $itemsAenviar = array();
    foreach ($order->get_items() as $item) {
        $product = $item->get_product();
        $product_SKU = $product ? $product->get_sku() : '';
        $producto_nombre = $item->get_name();
        $cantidad = $item->get_quantity();
        $total = $item->get_total();
        $porc_dcto = $product ? get_post_meta($product->get_id(), 'porc_dcto', true) : '';
        $cod_promo = $product ? get_post_meta($product->get_id(), 'cod_promocion', true) : '';

        $itemsAenviar[] = array(
            'EDET_NRO_ITEM' => count($itemsAenviar) + 1,
            // Incrementamos automáticamente el número de item
            'EDET_SKU' => $product_SKU,
            'EDET_DESC' => $producto_nombre,
            'EDET_CANT' => $cantidad,
            'EDET_PRECIO' => $total,
            'EDET_PORC_DCTO' => $porc_dcto,
            'EDET_COD_PROMO' => $cod_promo,
        );
    }


    // Obtener la fecha actual
    date_default_timezone_set('America/Asuncion');
    $now = date('Y-m-d\TH:i:s\Z');

    // Crear el arreglo de datos para la venta
    $venta = array(
        'ECO_PEDIDO' => 400000 + $numero_pedido,
        'ECO_PEDIDO_ALF' => $numero_proceso,
        'ECO_VENTA' => array(
            array(
                'ECO_TIPO' => '1',
                'ECO_MON' => '1',
                'ECO_FEC_PED' => $now,
                'ECO_ESTADO' => $estado_del_pedido,
                'ECO_MET_PAGO' => $medio_de_pago,
                'ECO_OPC_DELIVERY' => $metodo_envio,
                'ECO_DESCUENTO' => $total_descuento,
                'ECO_CUPON' => $cupon,
                'ECO_TOTAL' => $order_total,
            ),
        ),
        'ECO_DETALLE' => $itemsAenviar,
        'ECO_CLIENTE' => array(
            array(
                'CLI_CODIGO' => $cli_cogido,
                'CLI_RAZON_SOCIAL' => $customer_data['CLI_RAZON_SOCIAL'],
                'CLI_TIPO_DOC' => $customer_data['CLI_TIPO_DOC'],
                'CLI_NRO_DOC' => $customer_data['CLI_NRO_DOC'],
                'CLI_TELEFONO' => $telefono_cliente,
            ),
        ),
        'ECO_ENVIO' => array(
            array(
                'ECO_ENV_TIPO' => 1,
                'ECO_ENV_DIR' => $direccion_envio ?? 'SIN DIRECCION 123',
                'ECO_ENV_CIUDAD' => $pedido_ciudad ?? 'SIN CIUDAD',
                'ECO_ENV_DEP' => $depto_envio ?? 'SIN DEPARTAMENTO',
                'ECO_ENV_SUC' => $sucursal ?? $customer_data['ECO_ENV_SUC'],
                'ECO_ENV_TEL' => $telefono_cliente ?? 'SIN TELEFONO',
                'ECO_LATITUD' => $customer_data['ECO_LATITUD'] ?? 0,
                'ECO_LONGITUD' => $customer_data['ECO_LONGITUD'] ?? 0,
                'ECO_OBS' => $nota_pedido,
            ),
        ),
    );

    //$endpoint = 'https://api.dev.desarrollo.farmatotal.com.py/farma/next/ecommerce/pedido';
    $endpoint = 'https://api.farmatotal.com.py/farma/rws/ecommerce/save_order';

    $body = wp_json_encode(
        $venta,
        true,
        JSON_UNESCAPED_SLASHES,
        JSON_UNESCAPED_UNICODE
    );
    $options = [
        'method' => 'POST',
        'sslverify' => false,
        'body' => $body . PHP_EOL,
        'headers' => [
            'Content-Type' => 'application/json',
        ],
        'timeout' => 600,
        'redirection' => 10,
        'blocking' => true,
        'data_format' => 'body',
    ];
    //print_r($body);
    if ($customer_data['CLI_NRO_DOC'] != '9661000')
    {    
        $request = wp_remote_post($endpoint, $options);
    }
    //print_r($request);
    
    

    if (is_wp_error($request) || wp_remote_retrieve_response_code($request) != 200) {
        $response = wp_remote_retrieve_body($request);
        fwrite($TrackError, $response . PHP_EOL);
        update_post_meta($order->get_id(), 'pos_recibir_venta', $response . PHP_EOL);
        $message = sprintf('e-Commerce Sync Error: Nro Pedido: [%s] Respuesta ERP[%s]', sanitize_text_field($order->get_id()), sanitize_text_field($response . PHP_EOL));
        $order->add_order_note(__($message, 'ecom_recibir_venta'));
        fwrite($TrackError, $response . PHP_EOL);
        $venta = wp_json_encode($venta);
        $venta = $venta . PHP_EOL;
        fwrite($fp, $venta);
    } else {
        $response = wp_remote_retrieve_body($request);
        fwrite($TrackError, $response . PHP_EOL);
        $decode = json_decode(wp_remote_retrieve_body($request));
        update_post_meta($order->get_id(), 'pos_recibir_venta', $response . PHP_EOL);
        $message = sprintf('e-Commerce Sync Completada: Nro Pedido: [%s] Respuesta ERP[%s]', sanitize_text_field($order->get_id()), sanitize_text_field($decode->msg));
        $order->add_order_note(__($message, 'ecom_recibir_venta'));
        $order->update_status('completed');
        $venta = wp_json_encode($venta);
        $venta = $venta . PHP_EOL;
        fwrite($fp, $venta);
    }
    $order->add_order_note(__('Sucursal de Envío: '.$customer_data['ECO_ENV_SUC'], 'ecom_sucursal_envio'));
    $order->update_meta_data('json', $body . PHP_EOL);
    // Marcar el pedido como procesado para evitar ejecuciones duplicadas
    $order->update_meta_data('_order_processed', true);
    $order->save();
    fclose($fp);
}


/* JOB DE SINCRONIZACION AUTOMATICA*/

// Define la función para descargar y procesar los artículos
/*function descargar_y_procesar_articulos()
{
    $response = wp_remote_get('https://www.dev.desarrollo.farmatotal.com.py/api/wc-articulos-999999.php', array(
        'timeout'     => 600,
        'sslverify' => false,
    ));

    if ((!is_wp_error($response)) && (wp_remote_retrieve_response_code($response) === 200)) {
        $responseBody = json_decode($response['body'], true);
    } else {
        logger('Error ORDS Headers CronJob: ' . wp_remote_retrieve_response_code($response) . PHP_EOL);
    }

    // Elimina la marca de progreso al finalizar
    delete_transient('my_cron_job_in_progress');
}

add_action('job_procesar_articulos', 'descargar_y_procesar_articulos');

// Define la función para poner en cola la siguiente ejecución
function my_cron_job_queue()
{
    if (!get_transient('my_cron_job_in_progress')) {
        set_transient('my_cron_job_in_progress', true, 300);
        descargar_y_procesar_articulos();
    }
}

// Registra el cron job para que se ejecute cada 3 minutos
//add_action('my_cron_job_queue', 'my_cron_job_queue');

if (!wp_next_scheduled('my_cron_job_queue')) {
    // Calcula el tiempo para la próxima ejecución (3 minutos desde ahora)
    $next_run = time() + 180;
    wp_schedule_single_event($next_run, 'my_cron_job_queue');
}

// Asegúrate de limpiar cualquier programación anterior para evitar duplicaciones
wp_clear_scheduled_hook('my_cron_job_queue');



// Acción para procesar la solicitud al hacer clic en el botón "Sincronizar Productos"
add_action('admin_post_sincronizar_articulos', 'procesar_sincronizacion_articulos');

// Función para procesar la sincronización de los productos
function procesar_sincronizacion_articulos()
{
    // Verificar que el usuario tenga los permisos necesarios (por ejemplo, ser administrador)
    if (current_user_can('administrator')) {
        logger('Iniciando Sincronizacion desde el Dashboard del e-Commerce...');
        // Ejecutar la función para descargar y procesar los artículos
        descargar_y_procesar_articulos();

        // Iniciar la sesión para mostrar la notificación
        if (!session_id()) {
            session_start();
        }

        // Establecer una variable de sesión para indicar que la sincronización se ha completado
        $_SESSION['sincronizacion_completada'] = true;
    }

    // Redireccionar al dashboard después de la sincronización
    wp_redirect(admin_url('index.php'));
    exit;
}

// Función para mostrar la notificación después de la sincronización
function mostrar_notificacion_sincronizacion()
{
    if (!session_id()) {
        session_start();
    }

    // Verificar si la variable de sesión está establecida para mostrar la notificación
    if (isset($_SESSION['sincronizacion_completada']) && $_SESSION['sincronizacion_completada'] === true) {
        $message = 'La sincronización de artículos se ha completado correctamente.';
        $class = 'notice notice-success is-dismissible';
        $notice = '<div class="' . $class . '"><p>' . $message . '</p></div>';
        logger($notice);
        echo $notice;

        // Restablecer la variable de sesión para que la notificación solo se muestre una vez
        $_SESSION['sincronizacion_completada'] = false;
    }
}



// Función para mostrar el contenido del postbox personalizado
function contenido_postbox_personalizado()
{
    // Verificar que el usuario tenga los permisos necesarios (por ejemplo, ser administrador)
    if (current_user_can('administrator')) {
        // Agregar el contenido del postbox personalizado
        //echo '<p>Ejecuta el Script que Sincroniza las imágenes con los productos según el nombre de la imagen sea igual al SKU del producto</p>';
        //echo '<a href="' . admin_url('admin-post.php?action=ejecutar_insert_product_images') . '" class="button">Sincronizar Imágenes</a>';
        echo '<p>Ejecuta el Script que Sincroniza los Artículos del ERP</p>';
        //echo '<a href="' . admin_url('admin-post.php?action=sincronizar_articulos') . '" class="button">Sincronizar Productos</a>';
        echo '<a href="' . admin_url('admin-post.php?action=sincronizar_articulos') . '" class="button">Sincronizar Productos</a>';
    }
}

// Función para agregar el postbox personalizado en el área de Escritorio
function mostrar_postbox_personalizado()
{
    // Añadir el postbox personalizado en el dashboard
    wp_add_dashboard_widget(
        'custom_dashboard_widget',            // ID único del widget
        'Acciones Personalizadas',            // Título del widget
        'contenido_postbox_personalizado'    // Contenido del widget
    );
}

// Acción para registrar la función que muestra el postbox personalizado en el área de Escritorio
add_action('wp_dashboard_setup', 'mostrar_postbox_personalizado');*/



add_action('wp_head', 'custom_js');
function custom_js()
{
?>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZZNNYB9027"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-ZZNNYB9027');
    </script>

<!-- Pixel de Rastreo RWS -->
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-8FJXEXHK5L"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'G-8FJXEXHK5L');
    </script>

<!-- Pixel de Rastreo RWS -->



    <!-- Facebook Pixel Code -->
    <script>
        ! function(f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function() {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '786941389242101');
        fbq('track', 'PageView');
        fbq('track', 'AddToCart');
    </script>
    <noscript>
        <img height="1" width="1" src="https://www.facebook.com/tr?id=786941389242101&ev=PageView&noscript=1" />
    </noscript>
    <!-- End Facebook Pixel Code -->

    <meta name="facebook-domain-verification" content="0vhrz8o7hxr9vtijsxj4ytbj2vff6h" />
    
    <meta name="theme-color" content="#F16522" />



    <!-- Consulta de Existencias AJAX-->

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!--script src="https://code.jquery.com/jquery-3.6.4.min.js"></script-->
<!--script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script-->
<!--link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet"-->  

    <!--script type="text/javascript">
        jQuery(function($) {
            
$(document).ready(function () {
    // Verifica si la URL contiene la palabra "caja"
    if (window.location.href.indexOf('caja') !== -1) {
        var billingNroDoc = $('#billing_nro_doc');
        var billingTipoDoc = $('input[name="billing_tipo_doc"]');
        billingNroDoc.attr('maxlength','7');
        billingTipoDoc.on('change', function () {
            var tipoDocumento = getSelectedTipoDoc();
            // Verifica el formato correcto según el tipo de documento
            if (tipoDocumento == 1) {
                // Cédula de Identidad
                billingNroDoc.attr('maxlength','7');
            } else if (tipoDocumento == 2) {
                // RUC
                billingNroDoc.attr('maxlength','8');
            }
        });
        billingNroDoc.on('input', function () {
            var tipoDoc = getSelectedTipoDoc();
            console.log('Tipo de Documento Seleccionado: ' + tipoDoc);
            var sanitizedValue = sanitizeBillingNroDoc(this.value, tipoDoc);

            this.value = sanitizedValue;
        });

        function getSelectedTipoDoc() {
            for (var i = 0; i < billingTipoDoc.length; i++) {
                if (billingTipoDoc.eq(i).prop('checked')) {
                    return billingTipoDoc.eq(i).val();
                }
            }
            return null;
        }

function sanitizeBillingNroDoc(value, tipoDoc) {
    if (tipoDoc == 2) {
        // Si es RUC, permite solo números y un guion opcional al final
        console.log('Nuevo4 Formato RUC: 1234567-8');
        //return value.replace(/[^\d-]/g, '').replace(/(\d)-?$/g, '$1');
        //return value.replace(/[^\d-]/g, '').replace(/(\d{7})-?(\d{1})?$/, '$1-$2');
        return value.replace(/[^\d-]/g, '').replace(/(\d{7})-?(\d)?(\d*)$/, function(match, p1, p2, p3) {
            // Limitar la entrada de números adicionales después del primer carácter numérico posterior al guion
            return p1 + (p2 ? '-' + p2 : '') + (p3 ? '-' + p3.slice(0, 1) : '');
        });

    } else {
        console.log('Formato CI: 1234567');
        // Si es Cédula de Identidad, permite solo números
        return value.replace(/[^\d]/g, '');
    }
}


        function validateInput(value, tipoDoc) {
            // Verifica el formato correcto según el tipo de documento
            if (tipoDoc == 1) {
                // Cédula de Identidad
                if (!/^\d{7}$/.test(value)) {
                    console.log('Caracter no permitido. Formato CI: 1234567');
                    return 'Caracter no permitido. Formato CI: 1234567';
                }
            } else if (tipoDoc == 2) {
                // RUC
                if (!/^\d{7}(-\d)?$/.test(value)) {
                    console.log('Caracter no permitido. Formato RUC: 1234567-8');
                    return 'Caracter no permitido. Formato RUC: 1234567-8';
                }
            }

            return null; // No hay error
        }
    }
}); 
            
            
            
            
            
            
            $(document).ready(function() {
                if (window.location.href.indexOf("/caja/") > -1) {
                    $(".woocommerce-error").attr("style", "display: none");
                    $('button#place_order.button.alt').prop('disabled', true);

                    if ($('#billing_sucursal').val() == "") {
                        $('button#place_order.button.alt').prop('disabled', true);
                        Swal.fire(
                            'Oops',
                            'Debe seleccionar una sucursal para proceder a la compra ',
                            'warning'
                        );
                    } else {
                        $(ConsultaStock);
                    }
                    $('#billing_sucursal').change(ConsultaStock);
console.log(typeof jQuery.fn.block); // debería ser "function"
console.log(typeof $.fn.block);      // idem si $ es jQuery

                    function ConsultaStock() {
                        var order = $('div.order-review');
                        var payment = $('div.order-payment');
                        order.block({
                            message: null,
                            css: {
                                backgroundColor: 'transparent',
                                border: '0'
                            },
                            overlayCSS: {
                                backgroundColor: '#fff',
                                opacity: 0.8
                            }
                        });
                        payment.block({
                            message: null,
                            css: {
                                backgroundColor: 'transparent',
                                border: '0'
                            },
                            overlayCSS: {
                                backgroundColor: '#fff',
                                opacity: 0.8
                            }
                        });
                        var SucursalSelected = $("#billing_sucursal").val();
                        var list = {
                            STK_SUCURSAL: SucursalSelected,
                            STK_DETALLE: [],
                        };
                        <?php
                        /*$SucursalSelected = 1;
                        $ArticulosAConsultar = array();
                        $ArticulosAConsultarCount = 1;
                        foreach (WC()->cart->get_cart() as $cart_item_key => $cart_item) {
                            $item = $cart_item['data'] ?? 0;
                            $product_id = $cart_item['product_id'] ?? 0;
                            $SkuaBuscar = $item->sku ?? 0;
                            $CantidadWC = (int) $cart_item['quantity'] ?? 1;
                            $PorcDcto = get_post_meta($product_id, 'porcentaje_descuento', true) ?? 0;
                            $CodPromo = get_post_meta($product_id, 'codigo_promo', true) ?? 0;
                        ?>
                            list.STK_DETALLE.push({
                                STK_NRO_ITEM: <?php print_r($ArticulosAConsultarCount ?? 1); ?>,
                                STK_ARTICULO: "<?php print_r($SkuaBuscar ?? 0); ?>",
                                STK_CANTIDAD: <?php print_r($CantidadWC ?? 1); ?>,
                                STK_PORC_DCTO: 0,
                                STK_COD_PROMO: 0
                            });
                        <?php
                            $ArticulosAConsultarCount++;
                        }*/
                        ?>

                        //console.log(JSON.stringify(list));
                        $.ajax({
                            url: 'https://api.farmatotal.com.py/farma/next/ecommerce/stock',
                            type: 'POST',
                            timeout: 0,
                            contentType: 'application/json; charset=utf-8',
                            dataType: 'json',
                            data: JSON.stringify(list),
                            success: function(response) {
                                var len = response.value.length;
                                if (len > 0) {
                                    var ContarSinStock = 0;
                                    for (var i = 0; i < len; i++) {
                                        if (response.value[i].stk_cant_act < response.value[i].stk_cant_sol) {
                                            $('tr.cart_item.sku_' + response.value[i].stk_articulo + ' td.product-name').attr("style", "background-color: rgba(228,3,3,.3)");
                                            $('tr.cart_item.sku_' + response.value[i].stk_articulo + ' td.product-total').attr("style", "background-color: rgba(228,3,3,.3)");
                                            ContarSinStock++;
                                        } else {
                                            $('tr.cart_item.sku_' + response.value[i].stk_articulo + ' td.product-name').attr("style", "background-color: #82d45e");
                                            $('tr.cart_item.sku_' + response.value[i].stk_articulo + ' td.product-total').attr("style", "background-color: #82d45e");
                                        }
                                    }
                                    order.unblock();
                                    payment.unblock();
                                    console.log("Total Sin Stock: " + ContarSinStock);
                                    if (ContarSinStock >= 1) {
                                        $(".woocommerce-error").attr("style", "display: block");
                                        $('button#place_order.button.alt').prop('disabled', true);
                                        Swal.fire(
                                            'Oops',
                                            'Los articulos marcados no se encuentran disponible en la sucursal seleccionada. ',
                                            'warning'
                                        );
                                    } else {
                                        $(".woocommerce-error").attr("style", "display: none");
                                        $('button#place_order.button.alt').prop('disabled', false);
                                    }

                                }
                            }
                        });

                    }
                }

            })
        });
    </script-->
<!-- Consulta de Existencias AJAX con carga dinámica de BlockUI -->
<script type="text/javascript">
jQuery(function($){

  // 1) Inyecta BlockUI si todavía no existe
  function injectBlockUI(callback) {
    var scriptUrl = 'https://cdnjs.cloudflare.com/ajax/libs/jquery.blockUI/2.70/jquery.blockUI.min.js';
    if (typeof $.fn.block !== 'function') {
      var s = document.createElement('script');
      s.src = scriptUrl;
      s.onload = callback;
      document.head.appendChild(s);
    } else {
      callback();
    }
  }

  // 2) Prepara tu lógica una vez que BlockUI esté disponible
  function setupConsultaStock() {
    // Oculta errores y deshabilita el botón hasta seleccionar sucursal
    $(".woocommerce-error").hide();
    $('button#place_order.button.alt').prop('disabled', true);
    if ($('#billing_sucursal').val() == "") {
        $('button#place_order.button.alt').prop('disabled', true);
        Swal.fire(
            'Oops',
            'Debe seleccionar una sucursal para proceder a la compra ',
            'warning'
        );
    } else {
        if (window.location.href.indexOf('caja') !== -1) {
            $(ConsultaStock);
        }
    }
    // Si ya hay sucursal seleccionada al cargar, ejecuta ConsultaStock
    //if ($('#billing_sucursal').val()) {
    //  ConsultaStock();
    //}

    // Vincula el cambio de sucursal
    $('#billing_sucursal').off('change').on('change', function(){
      ConsultaStock();
    });
  }

  // 3) La función completa de ConsultaStock
  function ConsultaStock() {
    var order   = $('div.order-review'),
        payment = $('div.order-payment');

    // Bloquea ambas secciones con BlockUI
    order.block({
      message: null,
      css: { backgroundColor: 'transparent', border: '0' },
      overlayCSS: { backgroundColor: '#fff', opacity: 0.8 }
    });
    payment.block({
      message: null,
      css: { backgroundColor: 'transparent', border: '0' },
      overlayCSS: { backgroundColor: '#fff', opacity: 0.8 }
    });

    // Construye el payload
    var SucursalSelected = $("#billing_sucursal").val();
    var list = {
      STK_SUCURSAL: SucursalSelected,
      STK_DETALLE:  []
    };
    <?php
      $ArticulosAConsultarCount = 1;
      foreach (WC()->cart->get_cart() as $cart_item_key => $cart_item) {
          $item         = $cart_item['data'] ?? 0;
          $product_id   = $cart_item['product_id'] ?? 0;
          $SkuaBuscar   = $item->sku ?? 0;
          $CantidadWC   = (int) $cart_item['quantity'] ?? 1;
    ?>
      list.STK_DETALLE.push({
        STK_NRO_ITEM:   <?php echo $ArticulosAConsultarCount; ?>,
        STK_ARTICULO:   "<?php echo esc_js($SkuaBuscar); ?>",
        STK_CANTIDAD:   <?php echo $CantidadWC; ?>,
        STK_PORC_DCTO:  0,
        STK_COD_PROMO:  0
      });
    <?php
        $ArticulosAConsultarCount++;
      }
    ?>

    // Lanza la petición AJAX
    $.ajax({
      url: 'http://api.farmatotal.com.py/farma/next/ecommerce/stock',
      method: 'POST',
      contentType: 'application/json; charset=utf-8',
      dataType: 'json',
      data: JSON.stringify(list),
      timeout: 15000
    })
    .done(function(response) {
      var sinStock = 0;
      response.value.forEach(function(item) {
        var sel = 'tr.cart_item.sku_' + item.stk_articulo;
        var $cells = $(sel + ' td.product-name, ' + sel + ' td.product-total');
        if (item.stk_cant_act < item.stk_cant_sol) {
          $cells.css('background-color','rgba(228,3,3,0.3)');
          sinStock++;
        } else {
          $cells.css('background-color','#82d45e');
        }
      });

      if (sinStock) {
        $(".woocommerce-error").show();
        $('button#place_order.button.alt').prop('disabled', true);
        Swal.fire(
          'Oops',
          'Algunos artículos no están disponibles en la sucursal seleccionada.',
          'warning'
        );
      } else {
        $(".woocommerce-error").hide();
        $('button#place_order.button.alt').prop('disabled', false);
      }
    })
    .fail(function(jqXHR, textStatus) {
      Swal.fire(
        'Error',
        'No se pudo consultar el stock: ' + textStatus,
        'error'
      );
    })
    .always(function() {
      // Desbloquea UI
      order.unblock();
      payment.unblock();
    });
  }

  // 4) Inicia todo: inyecta BlockUI y luego setea los handlers
  /*setTimeout(function () {
    injectBlockUI(setupConsultaStock);
  }, 300);*/
    injectBlockUI(function(){
    // Al iniciar por primera vez
    //setupConsultaStock();

    // Cada vez que WooCommerce refresca el order review
    $('body').on('updated_checkout', setupConsultaStock);
  });

});


</script>

<?php
}


function obtener_sucursales()
{
    global $wpdb;

    // Obtener los términos de la taxonomía "inventories"
    $terms = get_terms(array(
        'taxonomy' => 'inventories',
        'hide_empty' => false,
    ));

    $sucursales = array();

    // Obtener la información de cada sucursal y guardarla en el array $sucursales
    foreach ($terms as $term) {
        $codigo_erp = get_term_meta($term->term_id, 'codigo_erp', true);
        $ciudad = get_term_meta($term->term_id, 'ciudad', true);

        if (!empty($codigo_erp)) {
            $sucursal = array(
                'id' => $term->term_id,
                'nombre' => $term->name,
                'direccion' => $term->description,
                'codigo_erp' => $codigo_erp,
                'ciudad' => $ciudad,
            );

            array_push($sucursales, $sucursal);
        }
    }

    return $sucursales;
}

function obtener_sucursales_agrupadas()
{
    global $wpdb;

    // Obtener los términos de la taxonomía "inventories"
    $terms = get_terms(array(
        'taxonomy' => 'inventories',
        'hide_empty' => false,
    ));

    $sucursales_agrupadas = array();

    // Agrupar las sucursales por ciudad utilizando el meta dato "codigo_erp" y "ciudad"
    foreach ($terms as $term) {
        $codigo_erp = get_term_meta($term->term_id, 'codigo_erp', true);
        $ciudad = get_term_meta($term->term_id, 'ciudad', true);

        if (!empty($codigo_erp) && !empty($ciudad)) {
            $sucursal = array(
                'id' => $term->term_id,
                'nombre' => $term->name,
                'direccion' => $term->description,
                'codigo_erp' => $codigo_erp,
                'ciudad' => $ciudad,
            );

            if (!array_key_exists($ciudad, $sucursales_agrupadas)) {
                $sucursales_agrupadas[$ciudad] = array();
            }

            array_push($sucursales_agrupadas[$ciudad], $sucursal);
        }
    }
    ksort($sucursales_agrupadas);
    return $sucursales_agrupadas;
}

function guardar_sucursal_seleccionada($order_id)
{
    if ($_POST['billing_sucursal']) {
        update_post_meta($order_id, 'billing_sucursal', sanitize_text_field($_POST['billing_sucursal']));
    }
}
add_action('woocommerce_checkout_update_order_meta', 'guardar_sucursal_seleccionada');


function agregar_select_sucursales2()
{
    $sucursales_agrupadas = obtener_sucursales_agrupadas();
    //if (count($sucursales_agrupadas) > 0) {
?>
    <p class="form-row form-row-wide" id="sucursal_field">
        <label for="billing_sucursal"><?php _e('Sucursal', 'woocommerce'); ?>&nbsp;<span class="required">*</span></label>
        <select class="select2" name="billing_sucursal" id="billing_sucursal" required="" data-placeholder="Elegí una sucursal…" disabled="">
            <option value=""><?php _e('Selecciona una sucursal', 'woocommerce'); ?></option>
            <?php foreach ($sucursales_agrupadas as $ciudad => $sucursales) : ?>
                <optgroup label="<?php echo $ciudad; ?>">
                    <?php foreach ($sucursales as $sucursal) : ?>
                        <option value="<?php echo $sucursal['codigo_erp']; ?>"><?php echo $sucursal['nombre']; ?> - <?php echo $sucursal['direccion']; ?></option>
                    <?php endforeach; ?>
                </optgroup>
            <?php endforeach; ?>
        </select>
    </p>
<?php
    //}
}

function agregar_select_sucursales() {
    $sucursales_agrupadas = obtener_sucursales_agrupadas();
    // Código ERP de la sucursal seleccionada (o null si no hay cookie)
    $selected_erp = obtener_codigo_erp_desde_cookie();
    ?>
    <p class="form-row form-row-wide" id="sucursal_field">
        <label for="billing_sucursal">
            <?php _e('Sucursal', 'woocommerce'); ?>&nbsp;<span class="required">*</span>
        </label>
        <select
            class="select2"
            name="billing_sucursal"
            id="billing_sucursal"
            required
            data-placeholder="<?php esc_attr_e('Elegí una sucursal…', 'woocommerce'); ?>"
        >
            <option value="">
                <?php _e('Selecciona una sucursal', 'woocommerce'); ?>
            </option>
            <?php foreach ($sucursales_agrupadas as $ciudad => $sucursales) : ?>
                <optgroup label="<?php echo esc_attr($ciudad); ?>">
                    <?php foreach ($sucursales as $sucursal) : 
                        $erp = $sucursal['codigo_erp'];
                        $nombre = $sucursal['nombre'];
                        $direccion = $sucursal['direccion'];
                        // ¿Es esta la opción seleccionada?
                        $sel = ($erp == $selected_erp) ? ' selected' : '';
                    ?>
                        <option 
                            value="<?php echo esc_attr($erp); ?>" 
                            <?php echo $sel; ?>
                        >
                            <?php echo esc_html("$nombre – $direccion"); ?>
                        </option>
                    <?php endforeach; ?>
                </optgroup>
            <?php endforeach; ?>
        </select>
    </p>
    <?php
}




//add_action('woocommerce_before_checkout_billing_form', 'agregar_select_sucursales', 10, 0);

/*function agregar_select_sucursales()
{
    $sucursales = obtener_sucursales();

    if (count($sucursales) > 0) {
    ?>
        <p class="form-row form-row-wide" id="sucursal_field">
            <label for="billing_sucursal"><?php _e('Sucursal', 'woocommerce'); ?>&nbsp;<span class="required">*</span></label>
            <select class="select2" name="billing_sucursal" id="billing_sucursal" required="" data-placeholder="Elegí una sucursal…">
                <option value=""><?php _e('Selecciona una sucursal', 'woocommerce'); ?></option>
                <?php foreach ($sucursales as $sucursal) : ?>
                    <?php if (!empty($sucursal['ciudad'])) : ?>
                        <optgroup label="<?php echo $sucursal['ciudad']; ?>">
                    <?php endif; ?>
                    <option value="<?php echo $sucursal['codigo_erp']; ?>"><?php echo $sucursal['nombre']; ?> - <?php echo $sucursal['direccion']; ?></option>
                    <?php if (!empty($sucursal['ciudad'])) : ?>
                        </optgroup>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </p>
    <?php
    }
}*/

// Mover el campo de selección de sucursales antes del campo "billing_city"
add_action('woocommerce_before_checkout_billing_form', 'agregar_select_sucursales', 9);



function agregar_select2_a_sucursal()
{
?>
    <script>
        jQuery(document).ready(function($) {
            $('#billing_sucursal').select2();
        });
    </script>
<?php
}
add_action('woocommerce_before_checkout_form', 'agregar_select2_a_sucursal', 5);

add_filter('woocommerce_cart_item_class', 'add_sku_to_cart_item_class', 10, 3);
function add_sku_to_cart_item_class($class, $cart_item, $cart_item_key)
{
    $product = $cart_item['data'];
    if ($product && is_object($product)) {
        $sku = $product->get_sku();
        if ($sku) {
            $class .= ' sku_' . $sku;
        }
    }
    return $class;
}


// Agregar acción para verificar la sucursal antes de realizar el pedido
add_action('woocommerce_checkout_process', 'verificar_sucursal_seleccionada');

function verificar_sucursal_seleccionada()
{
    if (empty($_POST['billing_sucursal'])) {
        wc_add_notice(__('Debe seleccionar una sucursal para proceder a la compra'), 'error');
    }
}

// Agregar filtro para hacer el campo "billing_sucursal" obligatorio
//add_filter('woocommerce_checkout_fields', 'hacer_campo_sucursal_obligatorio');

function hacer_campo_sucursal_obligatorio($fields)
{
    $fields['billing']['billing_sucursal']['required'] = true;
    return $fields;
}



function get_slider_images_for_today()
{
    // Obtener todas las imágenes que tienen el campo personalizado "slider" en true
    $args = array(
        'post_type' => 'attachment',
        'meta_query' => array(
            array(
                'key' => 'slider',
                'value' => '1', // True
                'compare' => '=',
            ),
        ),
    );

    $slider_images = get_posts($args);

    // Obtener el día actual en minúsculas
    //$today = current_time('Y-m-d');
    //$day = strtolower(date('l', strtotime($today)));

    // Establecer la configuración regional en español
    setlocale(LC_TIME, 'es_ES.utf8');

    // Obtener el día actual en minúsculas en español
    $today = current_time('Y-m-d');
    $day = strtolower(strftime('%A', strtotime($today)));

    //echo 'Día de la Semana: ' .$day. PHP_EOL;

    // Filtrar las imágenes para obtener las que deben mostrarse hoy
    $images_for_today = array();
    foreach ($slider_images as $image) {
        //echo 'Imagen del día: ' . $image->ID . PHP_EOL;
        // Obtener el valor serializado del campo "dias" para la imagen actual
        $serialized_days = get_post_meta($image->ID, 'dias', true);

        if ($serialized_days) {
            //echo 'Serialized Days: ' . json_encode($serialized_days, true). PHP_EOL;
            if (is_array($serialized_days) && in_array($day, $serialized_days)) {
                $images_for_today[] = wp_get_attachment_image_src($image->ID, 'full')[0];
            }
        }
    }

    return $images_for_today;
}


function get_slider_images_for_platforms()
{
    // Verificar si el usuario está en un dispositivo móvil o de escritorio
    if (wp_is_mobile()) {
        $platform = 'mobile';
    } else {
        $platform = 'desktop';
    }

    // Obtener todas las imágenes que tienen el campo personalizado "slider" en true
    $args = array(
        'post_type' => 'attachment',
        'meta_query' => array(
            array(
                'key' => 'slider',
                'value' => '1', // True
                'compare' => '=',
            ),
        ),
    );

    $slider_images = get_posts($args);
    debugg(json_encode($slider_images, true));
    print_r(json_encode($slider_images, true));

    // Establecer la configuración regional en español
    setlocale(LC_TIME, 'es_ES.utf8');

    // Obtener el día actual en minúsculas en español
    $today = current_time('Y-m-d');
    $day = strtolower(strftime('%A', strtotime($today)));

    // Filtrar las imágenes para obtener las que deben mostrarse hoy y para la plataforma correcta
    $images_for_today = array();
    foreach ($slider_images as $image) {
        // Obtener el valor serializado del campo "dias" para la imagen actual
        $serialized_days = get_post_meta($image->ID, 'dias', true);
        // Obtener el valor del campo "plataforma" para la imagen actual
        $platform_options = get_post_meta($image->ID, 'plataforma', true);

        debugg('Image: ' . $image->ID . ' - ' . $image->post_title . PHP_EOL . 'Serialized Days: ' . json_encode($serialized_days, true) . PHP_EOL . 'Platforms: ' . json_encode($platform_options, true) . PHP_EOL);

        if ($serialized_days && is_array($platform_options) && in_array($platform, $platform_options)) {
            if (is_array($serialized_days) && in_array($day, $serialized_days)) {
                $images_for_today[] = wp_get_attachment_image_src($image->ID, 'full')[0];
            }
        }
    }

    return $images_for_today;
}

function get_slider_images_for_today_platforms()
{
    // Verificar si es un dispositivo móvil o tablet
    $is_mobile = wp_is_mobile();
    $platform_key = $is_mobile ? 'mobile' : 'desktop';
    //print_r('WP: ' .$is_mobile . ' - Platform: ' .$platform_key);

    // Establecer la configuración regional en español
    setlocale(LC_TIME, 'es_ES.utf8');
    // Obtener el día actual en minúsculas en español
    $today = current_time('Y-m-d');
    $day = strtolower(strftime('%A', strtotime($today)));


    // Consulta personalizada para obtener imágenes
    $slider_images = get_posts(array(
        'post_type' => 'attachment',
        'posts_per_page' => -1,
        'meta_query' => array(
            'relation' => 'AND',
            array(
                'key' => 'slider',
                'value' => '1',
                'compare' => '=',
            ),
            array(
                'key' => 'dias',
                'value' => '"' . $day . '"',
                'compare' => 'LIKE',
            )/*,
            array(
                'key' => 'plataforma',
                'value' => '. $platform_key .' ,
                'compare' => '=',
            )*/
        ),
    ));
    
    //console_log('Images Sliders: ', $slider_images);

    $images_for_today = array();

    foreach ($slider_images as $image) {
        $platforms = get_post_meta($image->ID, 'plataforma', true);
        //console_log('ID: ' . $image->ID . ', Images Platforms: ', $platforms);
        $platform = !empty($platforms) ? $platforms[0] : ''; // Obtener el primer elemento o cadena vacía si no hay plataformas
        $images_for_today[] = array(
            'url' => wp_get_attachment_image_src($image->ID, 'full')[0],
            'platform' => $platform,
        );
    }

    return $images_for_today;
}

/*function custom_slider_shortcode()
{
    ob_start();

    $image_urls = get_slider_images_for_today_platforms();
    
    if(wp_is_mobile() == null){
        $is_mobile = 0;
    }else{
        $is_mobile = 1;
    }
    //print_r('is-mobile: ' . $is_mobile . ' - Original: '. wp_is_mobile());

    if (!empty($image_urls)) {
        
        if($is_mobile){
            // Contenedor para la plataforma mobile
            echo '<div class="slider-container mobile-container hide-desktop" id="mobile-container">';
            echo '<div class="slider hide-desktop">';
            foreach ($image_urls as $image) {
                if ($image['platform'] === 'mobile') {
                    echo '<div class="slide hide-desktop">';
                    echo '<img src="' . esc_url($image['url']) . '" alt="Slider Image" class="hide-desktop">';
                    echo '</div>';
                }
            }
            echo '</div>';
            echo '<div class="slider-navigation">';
            echo '<button class="prev-slide">&#8249;</button>';
            echo '<button class="next-slide">&#8250;</button>';
            echo '</div>';
            echo '</div>';
        }else{
            // Contenedor para la plataforma desktop
            echo '<div class="slider-container desktop-container hide-mobile" id="desktop-container">';
            echo '<div class="slider hide-mobile">';
            foreach ($image_urls as $image) {
                if ($image['platform'] === 'desktop') {
                    echo '<div class="slide hide-mobile">';
                    echo '<img src="' . esc_url($image['url']) . '" alt="Slider Image" class="hide-mobile">';
                    echo '</div>';
                }
            }
            echo '</div>';
            echo '<div class="slider-navigation">';
            echo '<button class="prev-slide">&#8249;</button>';
            echo '<button class="next-slide">&#8250;</button>';
            echo '</div>';
            echo '</div>';
        }
    }

    return ob_get_clean();
}
add_shortcode('custom_slider', 'custom_slider_shortcode');*/

function custom_slider_shortcode2()
{
    ob_start();

    $image_urls = get_slider_images_for_today_platforms();
    //console_log('Images Url: ', $image_urls);

    $is_mobile = wp_is_mobile() ? 1 : 0;

    if (!empty($image_urls)) {
        // CSS optimizado para Slick Slider
        echo '<style>
        /* Contenedor principal del slider */
        .custom-slider-container {
            width: 100%;
            position: relative;
            overflow: hidden;
        }
        
        /* Slider Slick */
        .custom-slider {
            width: 100%;
            height: 80vh;
            min-height: 400px;
            max-height: 700px;
        }
        
        /* Slides individuales */
        .custom-slider .slick-slide {
            height: 80vh;
            min-height: 400px;
            max-height: 700px;
            position: relative;
            overflow: hidden;
        }
        
        .custom-slider .slick-slide > div {
            height: 100%;
        }
        
        /* CLAVE: Imágenes que cubren todo el espacio */
        .custom-slider .slick-slide img {
            width: 100%;
            height: 100%;
            object-fit: cover !important;  /* Cubre todo el área */
            object-position: center center !important; /* Centra la imagen */
            display: block !important;
        }
        
        /* Asegurar que el track tenga la altura correcta */
        .custom-slider .slick-track {
            height: 100%;
        }
        
        .custom-slider .slick-list {
            height: 100%;
        }
        
        /* Flechas de navegación de Slick - Posicionamiento correcto */
        .custom-slider .slick-prev,
        .custom-slider .slick-next {
            position: absolute !important;
            top: 50% !important;
            transform: translateY(-50%) !important;
            z-index: 999 !important;
            width: 50px !important;
            height: 50px !important;
            background: rgba(0, 0, 0, 0.5) !important;
            border-radius: 50% !important;
            border: none !important;
            cursor: pointer !important;
        }
        
        .custom-slider .slick-prev {
            left: 20px !important;
        }
        
        .custom-slider .slick-next {
            right: 20px !important;
        }
        
        .custom-slider .slick-prev:hover,
        .custom-slider .slick-next:hover {
            background: rgba(0, 0, 0, 0.8) !important;
        }
        
        .custom-slider .slick-prev:before,
        .custom-slider .slick-next:before {
            font-size: 30px !important;
            color: white !important;
            text-shadow: none !important;
            line-height: 1 !important;
        }
        
        /* Asegurar que las flechas no se muevan */
        .custom-slider .slick-prev:focus,
        .custom-slider .slick-next:focus {
            outline: none !important;
        }
        
        /* Dots de navegación - Posicionamiento correcto */
        .custom-slider .slick-dots {
            position: absolute !important;
            bottom: 20px !important;
            left: 50% !important;
            transform: translateX(-50%) !important;
            display: flex !important;
            justify-content: center !important;
            list-style: none !important;
            padding: 0 !important;
            margin: 0 !important;
            z-index: 999 !important;
        }
        
        .custom-slider .slick-dots li {
            margin: 0 5px !important;
        }
        
        .custom-slider .slick-dots li button {
            width: 15px !important;
            height: 15px !important;
            border-radius: 50% !important;
            background: rgba(255, 255, 255, 0.5) !important;
            border: none !important;
            cursor: pointer !important;
            font-size: 0 !important;
            padding: 0 !important;
        }
        
        .custom-slider .slick-dots li button:before {
            display: none !important;
        }
        
        .custom-slider .slick-dots li.slick-active button {
            background: white !important;
        }
        
        /* Responsive - Mobile */
        @media (max-width: 768px) {
            .custom-slider,
            .custom-slider .slick-slide {
                height: 50vh;
                min-height: 300px;
                max-height: 400px;
            }
            
            .custom-slider .slick-prev,
            .custom-slider .slick-next {
                width: 40px !important;
                height: 40px !important;
            }
            
            .custom-slider .slick-prev {
                left: 10px !important;
            }
            
            .custom-slider .slick-next {
                right: 10px !important;
            }
            
            .custom-slider .slick-prev:before,
            .custom-slider .slick-next:before {
                font-size: 24px !important;
            }
            
            .custom-slider .slick-dots {
                bottom: 15px !important;
            }
            
            .custom-slider .slick-dots li button {
                width: 12px !important;
                height: 12px !important;
            }
        }
        
        /* Responsive - Mobile pequeño */
        @media (max-width: 480px) {
            .custom-slider,
            .custom-slider .slick-slide {
                height: 40vh;
                min-height: 250px;
                max-height: 350px;
            }
            
            .custom-slider .slick-prev,
            .custom-slider .slick-next {
                width: 35px !important;
                height: 35px !important;
            }
            
            .custom-slider .slick-prev:before,
            .custom-slider .slick-next:before {
                font-size: 20px !important;
            }
            
            .custom-slider .slick-dots {
                bottom: 10px !important;
            }
            
            .custom-slider .slick-dots li {
                margin: 0 3px !important;
            }
            
            .custom-slider .slick-dots li button {
                width: 10px !important;
                height: 10px !important;
            }
        }
        
        /* Clases de utilidad para mostrar/ocultar */
        .hide-mobile { display: block; }
        .hide-desktop { display: none; }
        
        @media (max-width: 768px) {
            .hide-mobile { display: none; }
            .hide-desktop { display: block; }
        }
        </style>';
        
        if($is_mobile){
            // Contenedor para mobile
            echo '<div class="custom-slider-container mobile-container hide-desktop">';
            echo '<div class="custom-slider mobile-slider hide-desktop">';
            foreach ($image_urls as $image) {
                if ($image['platform'] === 'mobile') {
                    echo '<div class="slide-item">';
                    echo '<img src="' . esc_url($image['url']) . '" alt="Slider Image" loading="lazy">';
                    echo '</div>';
                }
            }
            echo '</div>';
            echo '</div>';
        } else {
            // Contenedor para desktop
            echo '<div class="custom-slider-container desktop-container hide-mobile">';
            echo '<div class="custom-slider desktop-slider hide-mobile">';
            foreach ($image_urls as $image) {
                if ($image['platform'] === 'desktop') {
                    echo '<div class="slide-item">';
                    echo '<img src="' . esc_url($image['url']) . '" alt="Slider Image" loading="lazy">';
                    echo '</div>';
                }
            }
            echo '</div>';
            echo '</div>';
        }
        
        // JavaScript para inicializar Slick (solo si no está ya inicializado)
        echo '<script>
        jQuery(document).ready(function($) {
            // Configuración para desktop
            $(".desktop-slider").slick({
                dots: true,
                arrows: false,
                infinite: true,
                speed: 500,
                fade: true,
                cssEase: "linear",
                autoplay: true,
                autoplaySpeed: 5000,
                pauseOnHover: true,
                responsive: [
                    {
                        breakpoint: 1024,
                        settings: {
                            arrows: true,
                            dots: true
                        }
                    }
                ]
            });
            
            // Configuración para mobile
            $(".mobile-slider").slick({
                dots: true,
                arrows: false,
                infinite: true,
                speed: 500,
                fade: true,
                cssEase: "linear",
                autoplay: true,
                autoplaySpeed: 5000,
                pauseOnHover: true,
                responsive: [
                    {
                        breakpoint: 480,
                        settings: {
                            arrows: false,
                            dots: true
                        }
                    }
                ]
            });
        });
        </script>';
    }

    return ob_get_clean();
}



function custom_slider_shortcode()
{
    // 1. CARGA DE LIBRERÍAS (CSS y JS)
    // Esto asegura que Slick exista antes de intentar usarlo.
    // Se cargan desde CDN para velocidad.
    wp_enqueue_style('slick-css', 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css', array(), '1.8.1');
    wp_enqueue_style('slick-theme', 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css', array('slick-css'), '1.8.1');
    wp_enqueue_script('slick-js', 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js', array('jquery'), '1.8.1', true);

    ob_start();

    // 2. OBTENER DATOS
    $image_urls = get_slider_images_for_today_platforms();
    $is_mobile = wp_is_mobile() ? 1 : 0;

    if (!empty($image_urls)) {
        ?>
        <style>
            .custom-slider-container {
                width: 100%;
                position: relative;
                overflow: hidden;
                /* Evita saltos de layout antes de cargar JS */
                opacity: 0; 
                transition: opacity 0.5s ease;
            }
            /* Clase para mostrar el slider cuando ya cargó */
            .custom-slider-container.loaded {
                opacity: 1;
            }

            .custom-slider {
                width: 100%;
                /* Ajuste responsive base */
                height: 50vh; 
                min-height: 300px;
                max-height: 500px;
            }

            @media (min-width: 769px) {
                .custom-slider {
                    height: 80vh; 
                    min-height: 400px;
                    max-height: 700px;
                }
            }

            /* Slides */
            .custom-slider .slick-slide {
                height: 100%;
                position: relative;
            }

            .custom-slider .slick-slide div {
                 height: 100%; /* Fix para Slick que añade divs extra */
            }

            .custom-slider .slick-slide img {
                width: 100%;
                height: 100% !important; /* Forzar altura del contenedor */
                object-fit: cover !important;
                object-position: center center !important;
                display: block !important;
            }

            /* Navegación */
            .custom-slider .slick-prev, .custom-slider .slick-next {
                z-index: 50; /* Reducido de 999 para no tapar menús */
                width: 40px; height: 40px;
                background: rgba(0,0,0,0.3);
                border-radius: 50%;
                transition: background 0.3s;
            }
            .custom-slider .slick-prev { left: 15px; }
            .custom-slider .slick-next { right: 15px; }
            .custom-slider .slick-prev:hover, .custom-slider .slick-next:hover {
                background: rgba(0,0,0,0.8);
            }
            
            /* Puntos (Dots) */
            .custom-slider .slick-dots { bottom: 15px; }
            .custom-slider .slick-dots li button:before { font-size: 10px; color: white; opacity: 0.5; }
            .custom-slider .slick-dots li.slick-active button:before { opacity: 1; color: white; }

            /* Utilidades */
            .hide-mobile { display: block; }
            .hide-desktop { display: none; }
            
            @media (max-width: 768px) {
                .hide-mobile { display: none; }
                .hide-desktop { display: block; }
            }
        </style>

        <?php if($is_mobile): ?>
            <div class="custom-slider-container mobile-container hide-desktop">
                <div class="custom-slider mobile-slider">
                    <?php foreach ($image_urls as $image): ?>
                        <?php if ($image['platform'] === 'mobile'): ?>
                            <div class="slide-item">
                                <img src="<?php echo esc_url($image['url']); ?>" alt="Slider Mobile">
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php else: ?>
            <div class="custom-slider-container desktop-container hide-mobile">
                <div class="custom-slider desktop-slider">
                    <?php foreach ($image_urls as $image): ?>
                        <?php if ($image['platform'] === 'desktop'): ?>
                            <div class="slide-item">
                                <img src="<?php echo esc_url($image['url']); ?>" alt="Slider Desktop">
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>

        <script type="text/javascript">
        jQuery(document).ready(function($) {
            
            // Función para inicializar slider con manejo de errores
            function initSlider(selector, settings) {
                var $slider = $(selector);
                if ($slider.length > 0) {
                    // Verificamos si .slick existe
                    if (typeof $slider.slick === 'function') {
                        $slider.slick(settings);
                        // Mostrar el contenedor suavemente una vez cargado
                        $slider.closest('.custom-slider-container').addClass('loaded');
                    } else {
                        console.error('Slick Library not loaded yet for ' + selector);
                    }
                }
            }

            // Configuración común
            var commonSettings = {
                dots: true,
                arrows: false, // Default false, cambiamos en responsive
                infinite: true,
                speed: 600,
                fade: true,
                cssEase: "linear",
                autoplay: true,
                autoplaySpeed: 4000,
                pauseOnHover: true
            };

            // Desktop Init
            initSlider(".desktop-slider", $.extend({}, commonSettings, {
                arrows: true // Desktop tiene flechas
            }));

            // Mobile Init
            initSlider(".mobile-slider", $.extend({}, commonSettings, {
                arrows: false // Mobile sin flechas
            }));
            
        });
        </script>
        <?php
    }

    return ob_get_clean();
}
add_shortcode('custom_slider', 'custom_slider_shortcode');

// Función para registrar tamaños de imagen optimizados
function optimize_slider_images() {
    add_image_size('slider-desktop', 1920, 600, true);
    add_image_size('slider-mobile', 768, 400, true);
}
add_action('after_setup_theme', 'optimize_slider_images');






add_filter( 'woocommerce_rest_product_object_query', 'filter_products_by_brand_field', 999, 2 );
function filter_products_by_brand_field( $args, $request ) {
	if ( ! isset( $request['cod_interno'] ) ) {
		return $args;
	}
	
	$source_value = sanitize_text_field( $request['cod_interno'] );
	$source_meta_query = array(
		'key' => 'cod_interno',
		'value' => $source_value
	);
	
	if ( isset( $args['meta_query'] ) ) {
		$args['meta_query']['relation'] = 'AND';
		$args['meta_query'][] = $source_meta_query;
	} else {
		$args['meta_query'] = array();
		$args['meta_query'][] = $source_meta_query;
	}
	
	return $args;
}




// Mostrar el aviso en la página de checkout
//add_action('woocommerce_before_checkout_form', 'mostrar_aviso_pedidos_tarde');

// Mostrar el aviso en la página de checkout antes del botón de "Realizar pedido"
add_action('woocommerce_review_order_before_submit', 'mostrar_aviso_pedidos_tarde');

// Mostrar el aviso en la página de agradecimiento (thank you)
add_action('woocommerce_thankyou', 'mostrar_aviso_pedidos_tarde');

function mostrar_aviso_pedidos_tarde() {
    $hora_actual = date("H:i");
    $hora_limite = "22:30";

    if ($hora_actual >= $hora_limite) {
        wc_print_notice(__('Los pedidos realizados a partir de las 22:30 serán entregados al día siguiente.', 'woocommerce'), 'error');
    }
    
    /*wc_print_notice(__('Los pedidos realizados a partir de las <strong>22:30hs</strong> serán entregados al día siguiente. -- Hora Actual: ' . $hora_actual . ' -- Hora Limite: ' . $hora_limite, 'woocommerce'), 'error');*/
}

add_action ('wp_print_scripts', function () {
 if (wp_script_is ('wc-password-strength-meter', 'enqueued'))
 wp_dequeue_script ('wc-password-strength-meter');
}, 100);




/* Campo extra en registro de WooCommerce */
//add_action('woocommerce_register_form', 'ayudawp_nuevo_campo_registro_woo');
function ayudawp_nuevo_campo_registro_woo()
{
    woocommerce_form_field(
        'billing_razon_social',
        array(
            'type' => 'text',
            'required' => false, // esto añade un asterisco
            'label' => 'Nombres y Apellidos / Razón Social'
        ),
        (isset($_POST['billing_razon_social']) ? $_POST['billing_razon_social'] : '')
    );
    woocommerce_form_field(
        'billing_tipo_doc',
        array(
            'type' => 'select',
            'class'         => array('input-radio'),
            'required' => false, // esto añade un asterisco
            'placeholder'       => __('-- Seleccione un Tipo de Documento --'),
            'label' => 'Tipo de Documento',
            'options'     => array(
                '1' => __('Cédula de Identidad'),
                '2' => __('RUC')
                )
        ),
        (isset($_POST['billing_tipo_doc']) ? $_POST['billing_tipo_doc'] : '')
    );
    woocommerce_form_field(
        'billing_nro_doc',
        array(
            'type' => 'text',
            'required' => false, // esto añade un asterisco
            'label' => 'Nro. Documento'
        ),
        (isset($_POST['billing_nro_doc']) ? $_POST['billing_nro_doc'] : '')
    );
    woocommerce_form_field(
        'billing_phone',
        array(
            'type' => 'text',
            'required' => false, // esto añade un asterisco
            'label' => 'Teléfono'
        ),
        (isset($_POST['billing_phone']) ? $_POST['billing_phone'] : '')
    );
}
//Añadimos validación del campo
//add_action('woocommerce_register_post', 'ayudawp_validar_campos', 10, 3);
function ayudawp_validar_campos($username, $email, $errors)
{
    if (empty($_POST['billing_razon_social'])) {
        $errors->add('error_billing_razon_social', 'El campo: Razón Social, es obligatorio!');
    }
    if (empty($_POST['billing_tipo_doc'])) {
        $errors->add('error_billing_tipo_doc', 'El campo: Tipo de Documento, es obligatorio!');
    }
    if (empty($_POST['billing_nro_doc'])) {
        $errors->add('error_billing_nro_doc', 'El campo: Número de Documento, es obligatorio!');
    }
    if (empty($_POST['billing_phone'])) {
        $errors->add('error_billing_phone', 'El campo: Teléfono, es obligatorio!');
    }
}
//Añadimos el campo a la base de datos
//add_action('woocommerce_created_customer', 'ayudawp_guardar_campos_registro');
function ayudawp_guardar_campos_registro($customer_id)
{
    if (isset($_POST['billing_razon_social'])) {
        update_user_meta($customer_id, 'billing_razon_social', wc_clean($_POST['billing_razon_social']));
    }
    if (isset($_POST['billing_tipo_doc'])) {
        update_user_meta($customer_id, 'billing_tipo_doc', wc_clean($_POST['billing_tipo_doc']));
    }
    if (isset($_POST['billing_nro_doc'])) {
        update_user_meta($customer_id, 'billing_nro_doc', wc_clean($_POST['billing_nro_doc']));
    }
    if (isset($_POST['billing_phone'])) {
        update_user_meta($customer_id, 'billing_phone', wc_clean($_POST['billing_phone']));
    }
}





// Añadir campo personalizado al correo de pedido
add_action('woocommerce_email_customer_details', 'custom_woocommerce_email_order_details1', 20, 3);
function custom_woocommerce_email_order_details1($order, $sent_to_admin, $plain_text)
{
    $billing_sucursal = get_post_meta($order->get_id(), 'billing_sucursal', true);

    if (!empty($billing_sucursal)) {
        echo '<p><strong>' . __('Sucursal:', 'woocommerce') . '</strong> ' . esc_html($billing_sucursal) . '</p>';
    }
}

// Añadir campo personalizado al panel de administración de pedidos
add_action('woocommerce_admin_order_data_after_billing_address', 'custom_woocommerce_admin_order_details', 10, 1);
function custom_woocommerce_admin_order_details($order)
{
    $billing_sucursal = get_post_meta($order->get_id(), 'billing_sucursal', true);

    if (!empty($billing_sucursal)) {
        echo '<p><strong>' . __('Sucursal:', 'woocommerce') . '</strong> ' . esc_html($billing_sucursal) . '</p>';
    }
}

// Añadir campo personalizado al correo de pedido
add_action('woocommerce_email_order_meta', 'custom_woocommerce_email_order_details', 10, 4);
function custom_woocommerce_email_order_details($order, $sent_to_admin, $plain_text, $email)
{
    $billing_sucursal = get_post_meta($order->get_id(), 'billing_sucursal', true);

    if (!empty($billing_sucursal)) {
        echo '<p><strong>' . __('Sucursal:', 'woocommerce') . '</strong> ' . esc_html($billing_sucursal) . '</p>';
    }
}

add_filter( 'dgwt/wcas/indexer/searchable_set_items_count', function ( $count ) {
    return 10;
} );
add_filter( 'dgwt/wcas/indexer/readable_set_items_count', function ( $count ) {
    return 5;
} );
add_filter( 'dgwt/wcas/indexer/taxonomy_set_items_count', function ( $count ) {
    return 10;
} );
add_filter( 'dgwt/wcas/indexer/variations_set_items_count', function ( $count ) {
    return 5;
} );


function custom_elementor_product_query( $query ) {
    // Verifica si es la consulta del Product Carousel
    if ( isset( $query['post_type'] ) && 'product' === $query['post_type'] ) {
        // Agrega una condición meta_query para filtrar por el metadato "ind_destacado=S"
        $query['meta_query'] = array(
            array(
                'key' => 'ind_destacado', // nombre del metadato
                'value' => 'S', // valor que deseas filtrar
                'compare' => '=' // comparador
            ),
        );
    }
    return $query;
}

add_filter( 'elementor_pro/query/custom_featured_products', 'custom_elementor_product_query' );



function my_custom_query( $wp_query ) {
    // Custom query arguments
    $meta_query = array(
        array(
            'key'     => 'ind_destacado',
            'value'   => 'S',
            'compare' => '='
        )
    );

    $wp_query->set( 'meta_query', $meta_query );
    $wp_query->set( 'post_type', 'product' );
}

// Hook into Elementor's custom query filter
add_action( 'elementor/query/my_custom_query', 'my_custom_query' );


add_filter( 'dgwt/wcas/indexer/searchable_set_items_count', function ( $count ) {
    return 10;
} );
add_filter( 'dgwt/wcas/indexer/readable_set_items_count', function ( $count ) {
    return 5;
} );
add_filter( 'dgwt/wcas/indexer/taxonomy_set_items_count', function ( $count ) {
    return 10;
} );
add_filter( 'dgwt/wcas/indexer/variations_set_items_count', function ( $count ) {
    return 5;
} );



/**
 * Incluir funcionalidad de sincronización de pedidos con API
 */
if (!function_exists('ft_enviar_pedido_a_api')) {
    require_once get_stylesheet_directory() . '/orders-api.php';
    //include_once $_SERVER['DOCUMENT_ROOT'] . '/api/logger.php';
}



// Desactiva el runner asíncrono en shutdown
//add_filter( 'action_scheduler_allow_async_request_runner', '__return_false' );


// Impide guardar transients en la base
add_filter( 'pre_set_transient',          '__return_false' );
add_filter( 'pre_set_site_transient',     '__return_false' );

// Impide leer transients (devuelven siempre false/null)
add_filter( 'pre_transient',              '__return_null' );
add_filter( 'pre_site_transient',         '__return_null' );




add_filter( 'dgwt/wcas/indexer/searchable_set_items_count', function ( $count ) {
    return 10;
} );
add_filter( 'dgwt/wcas/indexer/readable_set_items_count', function ( $count ) {
    return 5;
} );
add_filter( 'dgwt/wcas/indexer/taxonomy_set_items_count', function ( $count ) {
    return 10;
} );
add_filter( 'dgwt/wcas/indexer/variations_set_items_count', function ( $count ) {
    return 5;
} );

// Archivo de tu plugin, o en functions.php

add_action('rest_api_init', function () {
    register_rest_route('custom-sync/v1', '/reindex', array(
        'methods'  => 'POST',
        'callback' => 'custom_sync_reindex_products',
        'permission_callback' => function () {
            // seguridad: solo aceptar si envían una key
            return isset($_SERVER['HTTP_X_API_KEY']) 
                && $_SERVER['HTTP_X_API_KEY'] === 'MI_SECRET_KEY';
        }
    ));
});

function custom_sync_reindex_products(WP_REST_Request $request) {
    $ids = $request->get_param('ids');

    if (empty($ids)) {
        // si no mandas ids, reindexa todo
        wc_update_product_lookup_tables();
        return array('status' => 'ok', 'message' => 'Reindexados todos los productos');
    }

    if (is_array($ids)) {
        foreach ($ids as $id) {
            wc_update_product_lookup_tables((int) $id);
        }
        return array('status' => 'ok', 'message' => 'Reindexados ' . count($ids) . ' productos');
    }

    return array('status' => 'error', 'message' => 'Parámetro ids inválido');
}


/**
 * Cargar librería Slick Carousel (CSS y JS)
 */
function enqueue_slick_library_assets() {
    // 1. Cargar CSS de Slick


    // 2. Cargar JS de Slick (Depende de jQuery, y se carga en el footer 'true')
    wp_enqueue_script(
        'slick-js', 
        'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js', 
        array('jquery'), 
        '1.8.1', 
        true 
    );
}
add_action('wp_enqueue_scripts', 'enqueue_slick_library_assets');